const userData = [
    {
        "id": "1",
        "name": "ryby",
        "team": "miami",
        "wins": 54,
        "losses": 10,
        "playoff_record": "3-4",
        "first_round_draft_picks": 7,
        "total_draft_picks": 27,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "2",
        "name": "mad",
        "team": "uga",
        "wins": 53,
        "losses": 13,
        "playoff_record": "10-3",
        "first_round_draft_picks": 21,
        "total_draft_picks": 55,
        "top_5_recruiting_classes": 5
    },
    {
        "id": "3",
        "name": "jimbo",
        "team": "lsu",
        "wins": 61,
        "losses": 15,
        "playoff_record": "12-2",
        "first_round_draft_picks": 9,
        "total_draft_picks": 32,
        "top_5_recruiting_classes": 3
    },
    {
        "id": "4",
        "name": "coy",
        "team": "texas",
        "wins": 50,
        "losses": 19,
        "playoff_record": "3-3",
        "first_round_draft_picks": 8,
        "total_draft_picks": 34,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "5",
        "name": "wookie",
        "team": "navy",
        "wins": 9,
        "losses": 5,
        "playoff_record": "0-0",
        "first_round_draft_picks": 0,
        "total_draft_picks": 1,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "6",
        "name": "jerred",
        "team": "oklahoma state",
        "wins": 56,
        "losses": 14,
        "playoff_record": 4-2,
        "first_round_draft_picks": 2,
        "total_draft_picks": 15,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "7",
        "name": "schley",
        "team": "penn state",
        "wins": 63,
        "losses": 10,
        "playoff_record": "3-5",
        "first_round_draft_picks": 3,
        "total_draft_picks": 26,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "8",
        "name": "rob",
        "team": "cincinnati",
        "wins": 59,
        "losses": 17,
        "playoff_record": "6-4",
        "first_round_draft_picks": 4,
        "total_draft_picks": 11,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "9",
        "name": "windy",
        "team": "tennessee",
        "wins": 46,
        "losses": 6,
        "playoff_record": "2-3",
        "first_round_draft_picks": 3,
        "total_draft_picks": 22,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "10",
        "name": "my bad",
        "team": "notre dame",
        "wins": 59,
        "losses": 11,
        "playoff_record": "2-4",
        "first_round_draft_picks": 8,
        "total_draft_picks": 39,
        "top_5_recruiting_classes": 3
    },
    {
        "id": "11",
        "name": "xman",
        "team": "usc",
        "wins": 48,
        "losses": 21,
        "playoff_record": "3-2",
        "first_round_draft_picks": 3,
        "total_draft_picks": 15,
        "top_5_recruiting_classes": 1
    },
    {
        "id": "12",
        "name": "orca",
        "team": "north carolina",
        "wins": 54,
        "losses": 16,
        "playoff_record": "0-5",
        "first_round_draft_picks": 2,
        "total_draft_picks": 31,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "13",
        "name": "sauce",
        "team": "oregon",
        "wins": 50,
        "losses": 20,
        "playoff_record": "2-3",
        "first_round_draft_picks": 6,
        "total_draft_picks": 34,
        "top_5_recruiting_classes": 1
    },
    {
        "id": "14",
        "name": "vapo",
        "team": "colorado",
        "wins": 47,
        "losses": 19,
        "playoff_record": "0-1",
        "first_round_draft_picks": 4,
        "total_draft_picks": 9,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "15",
        "name": "ozy",
        "team": "alabama",
        "wins": 16,
        "losses": 11,
        "playoff_record": "0-1",
        "first_round_draft_picks": 3,
        "total_draft_picks": 19,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "16",
        "name": "rellik",
        "team": "fsu",
        "wins": 45,
        "losses": 19,
        "playoff_record": "0-1",
        "first_round_draft_picks": 2,
        "total_draft_picks": 21,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "17",
        "name": "tolg",
        "team": "ucla",
        "wins": 13,
        "losses": 12,
        "playoff_record": "0-0",
        "first_round_draft_picks": 1,
        "total_draft_picks": 11,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "18",
        "name": "wonka",
        "team": "ohio state",
        "wins": 40,
        "losses": 24,
        "playoff_record": "0-2",
        "first_round_draft_picks": 7,
        "total_draft_picks": 27,
        "top_5_recruiting_classes": 2
    },
    {
        "id": "19",
        "name": "duv",
        "team": "clemson",
        "wins": 0,
        "losses": 0,
        "playoff_record": "0-0",
        "first_round_draft_picks": 0,
        "total_draft_picks": 0,
        "top_5_recruiting_classes": 0
    },

    {
        "id": "20",
        "name": "frosty",
        "team": "byu",
        "wins": 0,
        "losses": 0,
        "playoff_record": "0-0",
        "first_round_draft_picks": 0,
        "total_draft_picks": 0,
        "top_5_recruiting_classes": 0
    },
    {
        "id": "20",
        "name": "dream",
        "team": "texas tech",
        "wins": 0,
        "losses": 0,
        "playoff_record": "0-0",
        "first_round_draft_picks": 0,
        "total_draft_picks": 0,
        "top_5_recruiting_classes": 0
    },
]